language: c

compiler:
  - gcc
  - clang

dist: trusty
sudo: false

addons:
  apt:
    packages:
      - libcunit1-dev
      - libaio-dev
      - libssl-dev

before_script:
  - export MAKEFLAGS="-j$(nproc)"
  - if [ "$CC" = gcc ]; then
      wget https://downloads.sourceforge.net/project/astyle/astyle/astyle%203.0/astyle_3.0_linux.tar.gz;
      tar xf astyle_3.0_linux.tar.gz;
      pushd astyle/build/gcc;
      make;
      export PATH=$PWD/bin:$PATH;
      popd;
    fi
  - wget http://fast.dpdk.org/rel/dpdk-17.02.tar.xz
  - tar xf dpdk-17.02.tar.xz
  - pushd dpdk-17.02
  - make config T=x86_64-native-linuxapp-$CC
  - sed -i s/CONFIG_RTE_EAL_IGB_UIO=y/CONFIG_RTE_EAL_IGB_UIO=n/ build/.config
  - sed -i s/CONFIG_RTE_KNI_KMOD=y/CONFIG_RTE_KNI_KMOD=n/ build/.config
  - make
  - make install DESTDIR=.
  - export DPDK_DIR=$PWD/usr/local/share/dpdk/x86_64-native-linuxapp-$CC
  - popd

script:
  - ./scripts/check_format.sh
  - make CONFIG_WERROR=y
  - ./unittest.sh
